---
repos_to_install:
  - repo: https://github.com/exlskills/auth-server.git
    dest: /exlskills/auth-server
  - repo: https://github.com/exlskills/gql-server.git
    dest: /exlskills/gql-server
  - repo: https://github.com/exlskills/usi-server.git
    dest: /exlskills/usi-server
  - repo: https://github.com/exlskills/web-client.git
    dest: /exlskills/web-client            
  - repo: https://github.com/exlcode/exlcode.git
    dest: /exlskills/exlcode-ide
  - repo: https://github.com/exlcode/repl-web.git
    dest: /exlskills/exlcode-repl

process_config_files:
  - template: auth-server.env.j2
    dest: /exlskills/auth-server/.env
  - template: gql-server.env.j2
    dest: /exlskills/gql-server/.env
  - template: usi-server.env.j2
    dest: /exlskills/usi-server/.env        
  - template: web-client.env.j2
    dest: /exlskills/web-client/.env    

folders_to_run_npm_install:
  - /exlskills/auth-server
  - /exlskills/gql-server
  - /exlskills/usi-server
  - /exlskills/exlcode-ide/exlcode

folders_to_run_yarn_install:
  - /exlskills/web-client
  - /exlskills/exlcode-repl