---
load_courses: yes
load_data: yes

### ----------------------------------------------------------
### NETWORK FOOTPRINT
### ----------------------------------------------------------
host_dockernetwork_ip: 172.17.0.1

ports_on_host:
  mongo: 27017
  mysql: 3306
  memcached: 11211
  es: 9200
  keycloak: 8082
  auth_server: 3030
  gql_server: 8080
  spf_server: 3000
  exlcode_ide: 8000
  exlcode_repl: 8081

docker_compose:
  network_name: exlskills
  domain_suffix: exlskills

### ----------------------------------------------------------
### COMMON
### ----------------------------------------------------------
mongo_uri: "mongodb://{{ host_dockernetwork_ip }}:{{ ports_on_host.mongo }}"
mongo_db: exldev

memcached_url: "{{ host_dockernetwork_ip }}:{{ ports_on_host.memcached }}"

keycloak_client_id: exlskills
keycloak_realm: exlinc

node_base_image: node:8

entrypoint_nginx:
- nginx
- -g
- 'daemon off;'

### ----------------------------------------------------------
### STACK SCOPE
### ----------------------------------------------------------
projects_in_scope:

- name: auth-server
  project_type: generic-node-server
  port_on_host: "{{ ports_on_host.auth_server }}"
  container_port: 3030
  service_setup_method: run-image-dev
  clone_repo: yes
  repo: https://github.com/exlskills/auth-server.git
  folder: auth-server
  run_install: npm
  run_build: npm
  config_template: auth-server.env.j2
  config_file: .env
  prebuilt_image: exlskills/auth-server

- name: gql-server
  project_type: generic-node-server
  port_on_host: "{{ ports_on_host.gql_server }}"
  container_port: 8080
  service_setup_method: run-image-dev
  clone_repo: yes
  repo: https://github.com/exlskills/gql-server.git
  folder: gql-server
  run_install: npm
  run_build: npm
  config_template: gql-server.env.j2
  config_file: .env
  prebuilt_image: exlskills/gql-server

- name: spf-server
  project_type: generic-node-server
  port_on_host: "{{ ports_on_host.spf_server }}"
  container_port: 3000
  service_setup_method: run-image-dev
  clone_repo: yes
  repo: https://github.com/exlskills/spf-server.git
  folder: spf-server
  run_install: npm
  run_build: npm
  config_template: spf-server.env.j2
  config_file: .env
  prebuilt_image: TBD

- name: exlcode-ide
  project_type: aux-server
  port_on_host: "{{ ports_on_host.exlcode_ide }}"
  container_port: 80
  service_setup_method: build-image
  clone_repo: yes
  repo: https://github.com/exlcode/exlcode.git
  folder: exlcode-ide
  entrypoint: "{{ entrypoint_nginx }}"
  prebuilt_image: exlcode/ide-web

- name: exlcode-repl
  project_type: aux-server
  port_on_host: "{{ ports_on_host.exlcode_repl }}"
  container_port: 80
  service_setup_method: build-image
  clone_repo: yes
  repo: https://github.com/exlcode/repl-web.git
  folder: exlcode-repl
  run_install: yarn
  entrypoint: "{{ entrypoint_nginx }}"
  prebuilt_image: exlcode/repl-web

courses_to_load:
- repo: https://github.com/exlskills/course-java-basics.git
  folder: course-java-basics

test_users:
- username: jd
  firstName: Jane
  lastName: Doe
  email: jd@example.com
  password: jdTesting123
- username: jp
  firstName: John
  lastName: Public
  email: jp@example.com
  password: jpTesting123
