version: "3"

networks:
  exlskills:

services:
  
  installer:
    container_name: installer.exlskills
    build:
      context: docker_images/devstack_installer_user
      args:
        UNAME: ${EXL_DEVSTACK_USER}
        UID: ${EXL_DEVSTACK_UID}
        GID: ${EXL_DEVSTACK_GID}
    user: ${EXL_DEVSTACK_USER}
    networks:
      - exlskills  
    depends_on:
      - keycloak
      - mongodb
    working_dir: /hostlink
    environment:
      CODE_BASE_HOST_PATH: ${EXL_DEVSTACK_WORKSPACE}
      MGO_DB_NAME: ${MONGO_DB_NAME}
    volumes:
      - ./:/hostlink
      - ${EXL_DEVSTACK_WORKSPACE}:/exlskills
# TODO: this should be different for Mac
#      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  keycloak:
    container_name: keycloak.exlskills
    image: jboss/keycloak
    ports:
      - ${KEYCLOAK_HOST_PORT}:8080
    networks:
      - exlskills
    depends_on:
      - mysql
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      DB_VENDOR: mysql
      DB_ADDR: mysql.exlskills
      DB_USER: devstack_user
      DB_PASSWORD: devstack_pwd
    restart: unless-stopped

  mysql:
    container_name: mysql.exlskills
    image: mysql:5.7
#    command: --sql_mode=""
    ports:
      - ${MYSQL_HOST_PORT}:3306
    networks:
      - exlskills
    environment:
      MYSQL_ROOT_PASSWORD: 'Pa55w0rd'
      MYSQL_USER: 'devstack_user'
      MYSQL_PASSWORD: 'devstack_pwd'
      MYSQL_DATABASE: 'keycloak'
    volumes:
      - ${EXL_DEVSTACK_WORKSPACE}/var-lib-mysql:/var/lib/mysql
    restart: unless-stopped

  mongodb:
    container_name: mongo.exlskills
    image: mongo:3.6.7
    ports:
      - ${MONGO_HOST_PORT}:27017
    volumes:  
      - ${EXL_DEVSTACK_WORKSPACE}/data/mongo-db:/data/db
    networks:
      - exlskills      
    restart: unless-stopped

  memcached:
    container_name: memcached.exlskills
    image: memcached
    ports:
      - ${MEMCACHED_HOST_PORT}:11211
    networks:
      - exlskills      
    restart: unless-stopped

  elasticsearch:
    container_name: elasticsearch.exlskills
    image: elasticsearch:6.4.2
    ports:
      - ${ELASTICSEARCH_HOST_PORT}:9200
    volumes:  
      - ${EXL_DEVSTACK_WORKSPACE}/usr-share-elasticsearch:/usr/share/elasticsearch/data
    networks:
      - exlskills      
    restart: unless-stopped
