version: "3"

networks:
  exlskills:

services:

  auth-server:
    container_name: auth-server.exlskills
    image: node:8
    ports:
      - 3130:3030
    working_dir: /app
    volumes:
      - /home/ubuntu/exlskills-dev/auth-server:/app
    entrypoint:
      - npm
      - start
    networks:
      - exlskills

  exlcode-ide:
    container_name: exlcode-ide.exlskills
    build:
      context: /home/ubuntu/exlskills-dev/exlcode-ide
    ports:
      - 8100:80
    entrypoint:
      - nginx
      - -g
      - daemon off;
    networks:
      - exlskills

  exlcode-repl:
    container_name: exlcode-repl.exlskills
    build:
      context: /home/ubuntu/exlskills-dev/exlcode-repl
    ports:
      - 8181:80
    entrypoint:
      - nginx
      - -g
      - daemon off;
    networks:
      - exlskills

  gql-server:
    container_name: gql-server.exlskills
    image: node:8
    ports:
      - 8180:8080
    working_dir: /app
    volumes:
      - /home/ubuntu/exlskills-dev/gql-server:/app
    entrypoint:
      - npm
      - start
    networks:
      - exlskills

  usi-server:
    container_name: usi-server.exlskills
    image: node:8
    ports:
      - 5102:5002
    working_dir: /app
    volumes:
      - /home/ubuntu/exlskills-dev/usi-server:/app
    entrypoint:
      - npm
      - start
    networks:
      - exlskills

  web-client:
    container_name: web-client.exlskills
    image: nginx
    ports:
      - 4100:80
    volumes:
      - /home/ubuntu/exlskills-dev/web-client/build:/usr/share/nginx/html/learn
      - /home/ubuntu/exlskills-dev/web-client/nginx_config:/etc/nginx:ro
    networks:
      - exlskills