---
mongo_uri: "mongodb://{{ host_dockernetwork_ip }}:{{ ports_on_host.mongo }}"
mongo_db: exldev  

memcached_url: "{{ host_dockernetwork_ip }}:{{ ports_on_host.memcached }}"

stripe_pub_key: pk_test_havxVOg4IRAlXptV9FLhmfsP

keycloak_client_id: exlskills
keycloak_realm: exlinc

node_base_image: node:8

entrypoint_nginx:
      - nginx 
      - -g 
      - 'daemon off;'