---
host_dockernetwork_ip: 172.17.0.1

ports_on_host:
  mongo: 27117
  memcached: 11211
  keycloak: 8082
  auth_server: 3030
  gql_server: 8080
  usi_server: 5002
  web_client: 4000  
  exlcode_ide: 8000
  exlcode_repl: 8081

docker_compose:
  network_name: exlskills
  domain_suffix: exlskills
