---
- name: Convert and load course
  shell: go run main.go convert --from-format eocs --from-uri {{ course_folder }} --to-format eocs --to-uri {{ mongo_uri }}
  environment:
    MGO_DB_NAME: "{{ mongo_db }}"  
  args:
    chdir: "{{ gopath }}/src/github.com/exlskills/eocsutil"
  vars:
    gopath: "{{ lookup('env','GOPATH') }}"
  ignore_errors: yes

- name: Check ShowdownJS exited
  shell: ps -ax | grep -v grep | grep 'node --harmony showdownjs/server.js' | awk '{print $1}'
  register: running_showdownjs_process

- name: Kill running processes
  shell: kill {{ process_item }}
  loop: "{{ running_showdownjs_process.stdout_lines }}"
  loop_control:
    loop_var: process_item