---
- name: Clone Course Repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ base_local_path }}/courses/{{ item.folder }}"
    force: yes
  loop: "{{ courses_to_load }}"    

- name: Load Courses into DB
  include_tasks: convert_and_load_course.yml
  vars:
    course_folder: "{{ base_local_path }}/courses/{{ item.folder }}"
    suppress_conversion_error: "Yes"
  loop: "{{ courses_to_load }}"    
  
