---
- name: delete index
  uri:
    url: "{{ elasticsearch_url }}/{{ elasticsearch_base_index }}_en"
    method: DELETE
    validate_certs: no
    status_code: 200, 404
  when: recreate_index

- name: Check if Index Exists
  uri:
    url: "{{ elasticsearch_url }}/{{ elasticsearch_base_index }}_en"
    method: HEAD
    validate_certs: no
    status_code: 200, 404
  register: index_status

- name: Add Index
  uri:
    url: "{{ elasticsearch_url }}/{{ elasticsearch_base_index }}_en"
    method: PUT
    validate_certs: no
    body_format: json
    body: "{{ lookup('template', 'index_init.json.j2') }}"
  vars:
    text_analyzer: english
  when:
    - index_status.status != 200

- name: Update Index Settings
  block:
    - name: Close Index
      uri:
        url: "{{ elasticsearch_url }}/{{ elasticsearch_base_index }}_en/_close"
        method: POST
        validate_certs: no
    - name: Update Index Settings
      uri:
        url: "{{ elasticsearch_url }}/{{ elasticsearch_base_index }}_en/_settings"
        method: PUT
        validate_certs: no
        body_format: json
        body: "{{ index_settings_analysis | to_json }}"
      ignore_errors: yes
    - name: Open Index
      uri:
        url: "{{ elasticsearch_url }}/{{ elasticsearch_base_index }}_en/_open"
        method: POST
        validate_certs: no
  when:
    - index_status.status == 200

- name: Update Index
  uri:
    url: "{{ elasticsearch_url }}/{{ elasticsearch_base_index }}_en/_mappings/_doc"
    method: PUT
    validate_certs: no
    body_format: json
    body: "{{ index_properties | to_json }}"
  vars:
    text_analyzer: english
  when:
    - index_status.status == 200
