---
- name: delete index
  uri:
    url: "{{ es_url }}/learn_en"
    method: DELETE
    status_code: 200, 404
  when: recreate_index

- name: Check if Index Exists
  uri:
    url: "{{ es_url }}/learn_en"
    method: HEAD
    status_code: 200, 404
  register: index_status

- name: Add Index
  uri:
    url: "{{ es_url }}/learn_en"
    method: PUT
    body_format: json
    body: "{{ lookup('template', 'index_init.json.j2') }}"
  vars:
    text_analyzer: english
  when:
    - index_status.status != 200

- name: Update Index Settings
  block:
    - name: Close Index
      uri:
        url: "{{ es_url }}/learn_en/_close"
        method: POST
    - name: Update Index Settings
      uri:
        url: "{{ es_url }}/learn_en/_settings"
        method: PUT
        body_format: json
        body: "{{ index_settings_analysis | to_json }}"
      ignore_errors: yes
    - name: Open Index
      uri:
        url: "{{ es_url }}/learn_en/_open"
        method: POST
  when:
    - index_status.status == 200

- name: Update Index
  uri:
    url: "{{ es_url }}/learn_en/_mappings/_doc"
    method: PUT
    body_format: json
    body: "{{ index_properties | to_json }}"
  vars:
    text_analyzer: english
  when:
    - index_status.status == 200
