---
- name: Run 'npm run build' 
  shell: npm run build
  args:
    chdir: "/exlskills/{{ item.folder }}"
  loop: "{{ projects_in_scope }}" 
  when: item.run_build is defined and item.run_build == "npm"

- name: Run 'yarn run build' 
  shell: yarn run build
  args:
    chdir: "/exlskills/{{ item.folder }}"
  loop: "{{ projects_in_scope }}" 
  when: item.run_build is defined and item.run_build == "yarn"

# exlcode-ide work
- name: exlcode-ide 'npm run build-min' 
  shell: npm run build-min
  args:
    chdir: "/exlskills/{{ exlcode_ide_proj_config.folder }}/exlcode"
  when: 
    - exlcode_ide_proj_config is defined
    - exlcode_ide_proj_config.clone_repo
    - exlcode_ide_proj_config.clone_repo == "yes"