# ansible-playbook -vvv -e @.config.yml -e '{"recreate_index": true}' plays/elasticsearch-init.yml

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
  - include_role:
      name: init_elasticsearch
