---

# NOTE: /exlskills/ is the folder on the Installer - it is mapped to the Host's {{ codebase_hostpath }}

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
  - include_role:
      name: init_install
  - include_role:
      name: load_courses
