---
recreate_index: no

index_settings_analysis: &index_settings_analysis_struct
  analysis: 
    filter: 
      english_stop: 
        type: stop
        stopwords: _english_         
      english_keywords: 
        type: keyword_marker
        keywords:
          - example
      english_stemmer: 
        type: stemmer
        language: english
      english_possessive_stemmer: 
        type: stemmer
        language: possessive_english
    analyzer: 
      html_english: 
        type: custom
        tokenizer: standard
        filter: 
          - english_possessive_stemmer
          - lowercase
          - english_stop
          - english_keywords
          - english_stemmer
        char_filter:
          - html_strip

index_settings:
  number_of_shards : 1
  <<: *index_settings_analysis_struct

index_properties:
  properties:
    doc_type:
      type: keyword
    title:
      type: text
      analyzer: "{{ text_analyzer }}"
      fields:
        title_exact:
          type: text
          analyzer: standard
    headline:
      type: text
      analyzer: "{{ text_analyzer }}"
    text_content:
      type: text
      analyzer: "html_{{ text_analyzer }}"
    code_content:
      type: text
      analyzer: standard
    course_id:
      type: keyword
    unit_id:
      type: keyword
    section_id:
      type: keyword
    card_id:
      type: keyword
