---
- name: Clear (delete) compose_fragments directory
  file: 
      path: ../compose_fragments
      state: absent

- name: Create compose_fragments directory
  file:
    path: ../compose_fragments
    state: directory

- name: Prepare docker-compose.yml header
  template:
    src: 0-docker-compose-header.yml.j2
    dest: ../compose_fragments/0docker-compose-header.yml

- name: Set up generic-node-servers
  include_tasks: generic_node_server.yml
  vars:
    querystr: "[?name=='{{ item.name }}'] | [0]"
    project_config: "{{projects_in_scope|json_query(querystr)}}"
  loop: "{{ projects_in_scope }}" 
  when: item.project_type is defined and item.project_type == "generic-node-server"

- name: Set up web-client    
  include_tasks: web_client.yml
  vars:
    querystr: "[?name=='{{ item.name }}'] | [0]"
    project_config: "{{projects_in_scope|json_query(querystr)}}"   
  loop: "{{ projects_in_scope }}" 
  when: item.project_type is defined and item.project_type == "web-client"

- name: Set up aux-servers
  include_tasks: aux_server.yml
  vars:
    querystr: "[?name=='{{ item.name }}'] | [0]"
    project_config: "{{projects_in_scope|json_query(querystr)}}"   
  loop: "{{ projects_in_scope }}" 
  when: item.project_type is defined and item.project_type == "aux-server"

- name: Assemble into core docker-compose.yml
  assemble:
    src: ../compose_fragments
    dest: ../docker-compose.yml
