---
# DEPRECATED
- debug:
    msg: "{{ project_config }}"

- name: template run-image-dev
  template:
    src: web_client/run-image-dev.yml.j2
    dest: "../compose_fragments/{{ project_config.name }}.yml"
  vars:
    config: "{{ project_config }}"
  when: project_config.service_setup_method is defined and project_config.service_setup_method == "run-image-dev"

- name: template run-image-prod
  template:
    src: web_client/run-image-prod.yml.j2
    dest: "../compose_fragments/{{ project_config.name }}.yml"
  vars:
    config: "{{ project_config }}"
  when: project_config.service_setup_method is defined and project_config.service_setup_method == "run-image-prod"  

# NOTE: must use custom image as URIs are pre-coded into the SPA
- name: template pull-image
  template:
    src: web_client/pull-image.yml.j2
    dest: "../compose_fragments/{{ project_config.name }}.yml"
  vars:
    config: "{{ project_config }}"
  when: project_config.service_setup_method is defined and project_config.service_setup_method == "pull-image"  